# Generated by Django 5.2.17 on 2026-09-16 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
