# Generated by Django 5.2.17 on 2026-09-16 11:06

import employees.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=employees.fields.EncryptedCharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='esi',
            field=employees.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_deductions',
            field=employees.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pf',
            field=employees.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=employees.fields.EncryptedCharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=employees.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
