# Generated by Django 5.2.17 on 2026-09-21 11:05

import django.core.validators
import employees.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar_no',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar No. must be exactly 12 digits.', code='invalid_aadhar')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=employees.fields.EncryptedCharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='esic_no',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_no',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512, validators=[django.core.validators.RegexValidator('^[A-Z]{5}\\d{4}[A-Z]$', 'PAN No. format looks invalid (e.g. ABCDE1234F).', code='invalid_pan')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_no',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
