# Generated by Django 5.2.17 on 2026-09-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_seed_default_checklist_items'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payroll_start', models.DateField()),
                ('payroll_end', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField()),
                ('present_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('gross_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_salaries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='employees_s_organiz_4dd00d_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'employee', 'year', 'month'), name='unique_salary_record_per_month')],
            },
        ),
    ]
