# Generated by Django 5.2.17 on 2026-09-21 16:49

import employees.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_salaryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='other_deductions',
            field=employees.fields.EncryptedDecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
