# Generated by Django 5.2.17 on 2026-09-22 13:49

import employees.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_other_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='weekly_off',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text='Designated recurring weekly day off (0=Mon, 6=Sun)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='other_deductions',
            field=employees.fields.EncryptedDecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
