# Generated by Django 5.2.17 on 2026-09-29 09:42

import employees.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=employees.fields.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
